# Generated by Django 5.2.1 on 2025-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tradeattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="mt5_account_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mt5_last_fetch",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mt5_server",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
