# Generated by Django 5.2.1 on 2025-05-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_mt5_account_number_account_mt5_last_fetch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='gross_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='net_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
