# Generated by Django 5.2.1 on 2025-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailychecklisttemplate_dailychecklistitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdailychecklistprogress',
            options={'ordering': ['date', 'item']},
        ),
        migrations.AlterUniqueTogether(
            name='userdailychecklistprogress',
            unique_together={('user', 'item', 'date')},
        ),
    ]
