# Generated by Django 5.2.1 on 2025-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userdailychecklistprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailychecklistprogress',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
