# Generated by Django 5.2.1 on 2025-05-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userdailychecklistprogress_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('planned_stop', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('planned_target', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('planned_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_at', models.DateTimeField(auto_now_add=True)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('executed', 'Executed'), ('abandoned', 'Abandoned')], default='planned', max_length=10)),
                ('custom_checklist', models.TextField(blank=True, help_text='Comma-separated custom checklist items')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dailychecklisttemplate')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradePlanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_plan_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.tradeplan')),
            ],
        ),
    ]
