# Generated by Django 5.2.1 on 2025-05-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tradeplan_tradeplanattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=100)),
                ('confidence', models.IntegerField(blank=True, help_text='0-100 scale', null=True)),
                ('action', models.CharField(blank=True, help_text='E.g. Observed, Planned, Executed, Dropped', max_length=100)),
                ('trade_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tradeplan')),
            ],
        ),
    ]
