# Generated by Django 5.2.1 on 2025-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tradeplanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeplanevent',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='trade_plan_event_attachments/'),
        ),
    ]
