# Generated by Django 5.2.1 on 2025-05-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tradeplanevent_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeplanevent',
            name='attachment',
        ),
        migrations.CreateModel(
            name='TradePlanEventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trade_plan_event_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.tradeplanevent')),
            ],
        ),
    ]
