# Generated by Django 5.2.1 on 2025-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_quantity_trade_size_remove_trade_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
    ]
