# Generated by Django 5.2.1 on 2025-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_trade_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
