# Generated by Django 5.2.1 on 2025-06-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_trade_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='size',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='account',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='asset_class',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='execution_quality',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='plan_adherence',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='psychological_state',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='r_multiple',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='risk_per_trade',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='slippage',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trade',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tradeattachment',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.trade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_checklist',
            field=models.TextField(blank=True, help_text='Comma-separated checklist items'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discipline_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_progress',
            field=models.TextField(blank=True, help_text='Courses, books, key lessons, mistakes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psychological_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='core.account'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='review_frequency',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trading_style',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('swing', 'Swing'), ('scalp', 'Scalp'), ('investor', 'Investor')], max_length=32, null=True),
        ),
    ]
