# Generated by Django 5.2.1 on 2025-06-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_size_trade_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_checklist',
            field=models.TextField(blank=True, help_text='Comma-separated checklist items'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='core.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='discipline_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_progress',
            field=models.TextField(blank=True, help_text='Courses, books, key lessons, mistakes'),
        ),
        migrations.AddField(
            model_name='user',
            name='motivational_quote',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='psychological_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='review_frequency',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_profile',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trading_style',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('swing', 'Swing'), ('scalp', 'Scalp'), ('investor', 'Investor')], max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
