# Generated by Django 5.2.1 on 2025-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_trade_quantity_account_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeplan',
            name='post_trade_checklist',
        ),
        migrations.RemoveField(
            model_name='tradeplan',
            name='pre_trade_checklist',
        ),
    ]
